### ISSUE TITLE
Moving places and countries to Solr

### ISSUE THREAD

**Issue by skodapetr** [datagov-cz/nkd-formulare#124]
We need to prepare Solr cores first, they should be similar to the one for RUIAN but we need to clarify how to deal with places/countries without Czech title.

**Comment by jakubklimek** [comment]
We need a fallback mechanism. For EU vocabularies, when Czech label is missing, we need to display English one.

**Comment by jakubklimek** [comment]
Fallback mechanism implemented in the pipeline preparing codelists. "cs" and "en" in Solr now represents the text to be displayed in "cs" and "en" environments.
