### ISSUE TITLE
Make scrollbar dark in dark mode

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#128]
This is done like [this](https://github.com/opendata-mvcr/opendata-mvcr.github.io/blob/7b429832089c27178f9eea820149b44ea7b693fd/css/od.css#L50-L63) in CSS

**Comment by skodapetr** [comment]
Where are the "not dark scroll" bars? 
Also as of now, there seems to be no custom style as all is taken from Vuetify. Have you checked that it works with Vuetify?

**Comment by jakubklimek** [comment]
![image](https://user-images.githubusercontent.com/718827/80939829-20c10c00-8dde-11ea-85b5-70bb54b2e4c3.png)

I have not checked vuetify

**Comment by jakubklimek** [comment]
Seems that Vuetify does not do it. See [this post](https://itnext.io/dark-and-light-scrollbar-at-runtime-with-vue-and-vuetify-3809076e547d) for a possible fix. This is, of course, a minor issue.

**Comment by skodapetr** [comment]
Unfortunately, I do not have access to the post, can you copy the relevant content?

**Comment by skodapetr** [comment]
It is also not clear which scroll bar that is, from body? Is there only one in the whole application?
