### ISSUE TITLE
Update keyword fill tip

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#129]
It still says "add item by clicking on +" which is no longer valid. It should say "Klíčová slova oddělujte tabulátorem nebo entrem."/"Separate keywords by using tab or enter."

![image](https://user-images.githubusercontent.com/718827/80567572-bed75f80-89f5-11ea-80e6-63a0cd0b5485.png)

**Comment by skodapetr** [comment]
It is called hint :)
