### ISSUE TITLE
Misleading title: "Editace datové sady"

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#131]
![image](https://user-images.githubusercontent.com/718827/80570413-02809800-89fb-11ea-88b3-8250370ba91a.png)

This is displayed even when creating a new dataset, which may be misleading. This should be "Nová datová sada v NKOD", unless it actually is edit (related to #64 )

**Comment by skodapetr** [comment]
Is part of #64 as of now there is no such mode.
