### ISSUE TITLE
Add possibility to pre-fill dataset from URL by URL param

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#132]
Right now, we can fill the form in these ways:
1. manually
2. by editing existing dataset from DAV
3. by uploading existing file from disk
4. by pointing to URL of existing file

The primary use case for options 3 and 4 is enabling the user to use the prepared catalogization record stored in OFNs.

It would, however, be better, if there could be a link in the OFN, leading to the pre-filled form directly, i.e. as if user went for option 3 or 4, only one click (like option 2).

**Comment by skodapetr** [comment]
There is no plan to support OFN now, also the description is not specific enough to implement the functionality. 
With my best effort ... 
* you want to pre-import dataset from URL just like in 2. but make it a new dataset? 
* or do you want to have a button in the forms, just like for upload. Where user can pick OFN and import it? This would be indicated by the "only one click" comment.

**Comment by jakubklimek** [comment]
See [this OFN section](https://ofn.gov.cz/sportoviště/draft/#metadata). Right now, with Forms, you can either download the file and upload it to forms, or copy the URL and paste it in forms. This could be done easier, if in this section of the OFN, there could be a link to Forms including the URL of the [metadata file](https://ofn.gov.cz/sportoviště/draft/metadata/sportoviště.jsonld.txt), which would have the same result as download/upload, or URL copy&paste, but in one click.

**Comment by skodapetr** [comment]
So it would be effectively same as #137 ?

**Comment by jakubklimek** [comment]
No. The difference is that here we take the data from a JSON-LD file created by the form.
In #137 the data is loaded from NKOD.

**Comment by skodapetr** [comment]
Just to be clear, the url should be specified as "url" param as stated in the issue title. For example:

https://dev.nkod.opendata.cz/formulář/registrace-datové-sady?url=https%3A%2F%2Fofn.gov.cz%2Frozhraní-katalogů-otevřených-dat%2Fdraft%2Fpříklady%2Fdatová-sada.jsonld

**Comment by skodapetr** [comment]
We may also want to disable loading from file or URL .. but that is for consideration.
