### ISSUE TITLE
Edit dataset broken

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#144]
Click on edit in [this dataset](https://dev.nkod.opendata.cz/datová-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2FMV%2F98514) (or any other) and get "cant_import_dataset" page.

**Comment by skodapetr** [comment]
Invalid edit URL: 
https://dev.nkod.opendata.cz/formul%C3%A1%C5%99/registrace-datov%C3%A9-sady?url=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2FMV%2F98514

Can be used to test error message.
