### ISSUE TITLE
Expand shortened IRIs in JSON-LD values

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#152]
In the course of OFN release, it was decided that we do not want to shorten IRIs of, typically, code-list values in JSON-LD. Therefore, the output values need to be re-expanded.

This will also enable validation of correct code-lists via JSON Schema.

**Comment by skodapetr** [comment]
What does that mean? We not not  use prefixes like:

{
  "http://publications.europa.eu/resource/authority/file-type/": "format",
  "http://publications.europa.eu/resource/authority/frequency/": "frequency",
  "http://publications.europa.eu/resource/authority/country/": "country",
  "http://publications.europa.eu/resource/authority/continent/": "continent",
  "http://publications.europa.eu/resource/authority/place/": "place",
  "http://publications.europa.eu/resource/authority/data-theme/": "theme",
  "http://eurovoc.europa.eu/": "euroVoc",
  "https://rpp-opendata.egon.gov.cz/odrpp/zdroj/orgán-veřejné-moci/": "ovm",
}

and use full URL for those values instead?

**Comment by jakubklimek** [comment]
Yes
