### ISSUE TITLE
Output JSON should be almost valid against JSON schema for LKOD

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#158]
https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/draft/schémata/datová-sada.json

The only missing field will be `poskytovatel` in the case of a record for NKOD.

**Comment by skodapetr** [comment]
@jakubklimek  can you desribe how should we do the modifications?

For example in current version keywords is a language map, but in given schema, keywords is an array of language maps. 

Next you state that distribution must have IRI, so we should always export blank nodes?

Similar with přístupové_url. 

As far as I'm concerned this is goot to MANUALY validate the test data with, but there is missing "how" should the changes be resolved.

**Comment by jakubklimek** [comment]
@skodapetr the keywords issue is issue with the schema, see https://github.com/linkedpipes/dcat-ap-forms/issues/153 - i will work on that.

As to distributions and services - for NKOD, blank nodes (as done currently) are fine. For LKODs, distribution IRIs can be based on the dataset IRI.

What is the problem with přístupové_url?
