### ISSUE TITLE
Remove proprietary type from output

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#159]
Currently, the output contains:
```json
"typ": [
    "Datová sada",
    "https://data.gov.cz/slovník/nkod/typ-datové-sady-dle-zdroje/Formulář"
  ],
```
However, `https://data.gov.cz/slovník/nkod/typ-datové-sady-dle-zdroje/Formulář` is added by the NKOD harvesting process and should not be included in the output of the form.

**Comment by skodapetr** [comment]
I assume this holds true for both export for delete and export for edit /new as it is not stated otherwise.

**Comment by jakubklimek** [comment]
yes
