### ISSUE TITLE
Add returnUrl parameter

### ISSUE THREAD

**Issue by skodapetr** [datagov-cz/nkd-formulare#164]
We need to add _returnUrl_ to the URL query part, if the parameter is set then instead of exporting the data using download the data are send using POST method to URL specified by _returnUrl_.

This issue should implement requirement described in https://github.com/opendata-mvcr/lkod/issues/3

**Comment by jakubklimek** [comment]
@skodapetr OK, it seems to be POSTing. Shouldn't the browser then follow the returned redirect?

Specifically, the format of the POST seems the same as the expected POST input.
Naturally, I tried setting returnUrl to the URL of the form itself - I would expect to end up in a POST pre-filled (#163 ) form after POSTing.

**Comment by skodapetr** [comment]
Well it won't work, as the reponse of the POST contain the data the follow-up redirect does not. So you should get a clear form instead.
