### ISSUE TITLE
Add support for third-party data

### ISSUE THREAD

**Issue by skodapetr** [datagov-cz/nkd-formulare#165]
In order to allow easy integration with third party software we need to provide a way how to work with custom data - for example user identification/security token/... 

Based on https://github.com/opendata-mvcr/lkod/issues/4

**Comment by skodapetr** [comment]
The post JSON object may contain field ```userData``` with thirt-party provided data.

**Comment by jakubklimek** [comment]
@skodapetr Can you provide a workflow of how this can be tested? I am not sure how to test the initial POST step (#163 )

**Comment by skodapetr** [comment]
It is similar, you just need to include ```userData``` next to ```formData```.
