### ISSUE TITLE
Allow operator to set prefix used in HTML includes

### ISSUE THREAD

**Issue by skodapetr** [datagov-cz/nkd-formulare#169]
This will improve usability with POST and when the content is served via proxy on another URL. 
The operator should be able to set the prefix via the configuration, where default is "." - meaning relative paths are used (same as now).

**Comment by skodapetr** [comment]
The prefix can now be set using configuration property ```resources_url_prefix```.

**Comment by skodapetr** [comment]
@jakubklimek We should use this on demo instance, to allow experiment using third party proxy gates.

**Comment by jakubklimek** [comment]
@skodapetr done
