### ISSUE TITLE
Navigation to first step breaks history and hides step buttons

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#17]
When going from DAV to DCAT-AP-FORMS, I navigate to https://dev.nkod.opendata.cz/formulář/. I get redirected to https://dev.nkod.opendata.cz/formulář/#/ and then to https://dev.nkod.opendata.cz/formulář/#/?step=1. These are two steps and I need to click on "back" twice to get back to DAV. 

Besides that, when I navigate back to https://dev.nkod.opendata.cz/formulář/#/, the bottom button navigation disappears.

**Comment by skodapetr** [comment]
This should have been two issues. 
1) Missing button
2) Redirects

**Comment by skodapetr** [comment]
The landing IRI for dialog edit should be `http://localhost/#/dataset` not `http://localhost/`.
