### ISSUE TITLE
Allow download of invalid record

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#172]
We should allow download of invalid record.
The use case is that someone starts with a draft, wants to save it and continue some other time.
It should be basically just not disabling the download button.

**Comment by psiotwo** [comment]
Whether the user whether he is downloading an invalid draft, or a valid submittable version should be clearly visually distinguished in the UI IMO

**Comment by jakubklimek** [comment]
It is now distinguished by the validation result message, which is right above the download button.

We might emphasize it by also changing the download button color and text.
