### ISSUE TITLE
Add support for "conformsTo" in Data Service

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#173]
Should be similar to "specifikace" on Dataset, with appropriate adjustments in labels for data service (omit OFNs). Value is a list of URLs.

**Comment by skodapetr** [comment]
We need to add labels to (bottom):
https://github.com/linkedpipes/dcat-ap-forms/blob/develop/client/dataset/labels-cs.js
https://github.com/linkedpipes/dcat-ap-forms/blob/develop/client/dataset/labels-en.js
