### ISSUE TITLE
STIRData: typed literals and URI values are plain literals.

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#187]
This was solved by a JSON-LD context before, which is probably why it is missing now.

Involves:
- dcat:startDate, dcat:endDate (should be xsd:dateTime)
- dcat:downloadURL dcat:accessURL (should be IRI)

**Comment by jakubklimek** [comment]
Not quite:
![image](https://user-images.githubusercontent.com/718827/107547619-efc40200-6bcd-11eb-817c-ae2ae5fafd2e.png)

**Comment by jakubklimek** [comment]
In addition:

- temporalResolution - now is an IRI, should be xsd:duration
- spatialResolutionInMeters - now a string, should be xsd:integer

**Comment by jakubklimek** [comment]
Duration still wrong. Should be xsd:duration
```json
 "http://www.w3.org/ns/dcat#temporalResolution": {
    "@value": "P1D",
    "@type": "http://www.w3.org/2001/XMLSchema#integer"
  },
```

**Comment by skodapetr** [comment]
Can¨t you just test all of them at once? It is not like they are all changin each time I commit a change.

**Comment by jakubklimek** [comment]
I did: https://github.com/linkedpipes/dcat-ap-forms/issues/187#issuecomment-776882472

**Comment by skodapetr** [comment]
Ok, so not Duration is wrong but temporalResolution.
