### ISSUE TITLE
Navigating back does not work when clicking on 1-2-3 steps

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#188]
When I click on, let's say, 2 - Distribution, and press Back (in the browser), nothing happens. It could work normally.

**Comment by jakubklimek** [comment]
Still not working correctly:

1. Go to https://dev.nkod.opendata.cz/datové-sady and open Local catalog registration
2. Click on Step 2
3. Click on Step 1
4. Try to go back to DAV

**Comment by skodapetr** [comment]
That is catalog registration not dataset registration as in the issue - different component.
