### ISSUE TITLE
Search for Praha 12 causes 400 bad request

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#196]
Try searching like this:
![image](https://github.com/linkedpipes/dcat-ap-forms/assets/718827/62b27280-3c0f-426f-9841-ba1275c99cd2)

**Comment by skodapetr** [comment]
Seems to be caused by missing quotes around the name, thus a query with a space is invalid returning 400.

**Comment by jakubklimek** [comment]
> Seems to be caused by missing quotes around the name, thus a query with a space is invalid returning 400.

OK, so this means we need to escape spaces when they appear in the query?
