### ISSUE TITLE
Update the frequency codelist or make it load from Solr

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#201]
https://op.europa.eu/cs/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/frequency

related to #200

**Comment by skodapetr** [comment]
We have a limit to 1048576 items in a codelist, that should be more then enough for some time. Anyway once the codelists gets larger we should not fetch them to client side at all anyway.
