### ISSUE TITLE
When spatial coverage is left at default or loaded value, it is shown as IRI in summary

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#21]
![image](https://user-images.githubusercontent.com/718827/44020550-941a84a2-9ee2-11e8-96ef-bdbe38ce8603.png)

This was loaded from IRI, therefore not selected using the component. This is probably why it is shown as IRI, not label.

**Comment by skodapetr** [comment]
Could you provide the URL of the dataset?

**Comment by jakubklimek** [comment]
For the default case, just open https://dev.nkod.opendata.cz/formulář/#/registrace-datové-sady?krok=1 and click on "Shrnutí". For import, try the same with https://dev.nkod.opendata.cz/formulář/#/registrace-datové-sady?url=https://data.gov.cz/zdroj/datové-sady/MDopravy/225010433&krok=1

**Comment by jakubklimek** [comment]
The same goes for distributions - media type and file format is not shown in the summary even though it is filled in.
![image](https://user-images.githubusercontent.com/718827/44265698-fef9ad00-a227-11e8-9462-178f5f4490ba.png)

**Comment by skodapetr** [comment]
Next time please create a new issue.
