### ISSUE TITLE
Every form generates a "Update CKAN API IRI" error in console on access

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#27]
![image](https://user-images.githubusercontent.com/718827/44031014-e387f752-9f02-11e8-98cf-889cba530fa4.png)

**Comment by skodapetr** [comment]
Yes, to remind us that we need to set the CKAN IRI [here](https://github.com/linkedpipes/dcat-ap-forms-vue/blob/master/client/catalog/edit/codelists/catalog-type.js#L3). Once the IRI is valid we can remove the error message.

**Comment by jakubklimek** [comment]
It is valid
