### ISSUE TITLE
Change Catalog registration/delete messages

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#33]
This is related to #31 and #32.

Now, LKOD URL is used as the IRI for the Catalog. This is a bit unfortunate. The following changes are necessary:
1) Catalog registration - the API URL will be attached using `dcat:endpointURL`, the catalog itself will be a blank node
2) Catalog deletion - The form will be called with a (NKOD assigned) Catalog IRI, similarly to how it is done for datasets (a named graph with the IRI will be in the NKOD endpoint). In there, the data corresponding to the registration message will be present to be displayed. The catalog deletion message will use the catalog IRI (not endpoint IRI), type `dcat:Catalog`, and the withdrawn status as in dataset deletion message.

**Comment by jakubklimek** [comment]
Example registration (in Turtle), not including unchanged properties:
```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix nkod: <https://data.gov.cz/slovník/nkod/> .

[] a dcat:Catalog, nkod:DcatApSparql ;
     dcat:endpointURL "https://data.cssz.cz/sparql"^^xsd:anyURI .
```

Example catalog deletion:
```turtle
<https://data.gov.cz/zdroj/lkod/12345> a dcat:Catalog ;
         adms:status status:Withdrawn .
```

Where `https://data.gov.cz/zdroj/lkod/12345` is the Catalog IRI assigned to the registered one by NKOD

**Comment by skodapetr** [comment]
Any data on dev for testing?

**Comment by jakubklimek** [comment]
Yes, the data is now in dev.nkod.opendata.cz
