### ISSUE TITLE
Připomínky k formuláři registrace datové sady v NKOD - Podmínky užití distribuce 

### ISSUE THREAD

**Issue by michalkuban** [datagov-cz/nkd-formulare#35]
Připomínky k formuláři https://nkod.nakit.opendata.cz/formulář/#/registrace-datové-sady

U položek, které se týkají Podmínek užití distribuce, tak v závislosti na vybrané hodnotě dochází k odemknutí dalších položek (např. vybere se u položky „Autorské dílo“ hodnota „Autorské dílo licencované CC BY 4.0“ a odemkne se položka „Jména autorů díla“). Pokud se nově odemknutá položka vyplní a zase se zpětně změní hodnota předchozí položky, která nově odemknutou položku opět zamkne, tak nedochází ke smazání této již vyplněné položky. Do vygenerovaného souboru .jsonld se text v zamčené položce správně nedostává.

Pokud má daná datová sada více distribucí, tak se nelze mezi distribucemi přepínat klikem na kolečka, ačkoliv kolečka na stisk reagují. 

_Připomínky byly zaslány zástupci ČSSZ v rámci Pracovní skupiny pro otevřená data._

**Comment by jakubklimek** [comment]
Toto je schválně. Pro situaci, kdy si někdo vyplní třeba CC-BY a autora, pak přepne na jiný druh licence a pak zpět, aby se mu autor nesmazal.

**Comment by jakubklimek** [comment]
Co se týče klikání na kolečka, na popisovaný problém jsem nenarazil.
