### ISSUE TITLE
Eurovoc topic labels missing in chips

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#39]
I can search for and enter topics, however, their labels are then missing in the chips
![image](https://user-images.githubusercontent.com/718827/48260086-794a5f80-e41a-11e8-8e48-2482d21740c8.png)

**Comment by skodapetr** [comment]
![image](https://user-images.githubusercontent.com/3341693/48260531-07731580-e41c-11e8-9637-091fcbee4ae0.png)

Next time include at least server or whether it is create or edit.
