### ISSUE TITLE
Připomínky k formuláři registrace datové sady v NKOD - upozornění na nepodporovaný prohlížeč IE10

### ISSUE THREAD

**Issue by michalkuban** [datagov-cz/nkd-formulare#41]
Nefunguje pod IE 10, který máme v celém úřadu (v tomto případě doporučuji upozornit uživatele přímo na stránce, že používá nepodporovaný prohlížeč – jinak nelze poznat, zda není chyba na straně NKOD).

_Připomínka byla vznesena ze strany ČTÚ v rámci Pracovní skupiny pro otevřená data._

**Comment by jakubklimek** [comment]
IE10 už je tak zastaralý, že v něm vůbec nefungují technologie, na kterých je NKOD postaven. Nelze tedy ani zobrazit příslušnou chybovou hlášku. Toto je problém přílišné zastaralosti SW vybavení uživatele v takové míře, že to v NKOD nelze řešit.

I pro zastarávající Windows 7 je k dispozici update na IE11.
Ten je nicméně už také zastaralý. Někde je třeba udělat hranici, odkud to prostě bude rozbité, a ta je u nás pro Microsoft prohlížeče IE11 a i to bude v blízké budoucnosti bude za hranicí - Nástupnický MS Edge už je ve verzi 16.

To, že chyba není na straně NKOD, lze poznat ověřením v jiném prohlížeči jako třeba Chrome, Firefox, Opera, Safari, Vivaldi apod. v aktuálních verzích.
