### ISSUE TITLE
Připomínky k formuláři registrace datové sady v NKOD  - označení povinných údajů 

### ISSUE THREAD

**Issue by michalkuban** [datagov-cz/nkd-formulare#42]
Označit povinné údaje na vyplnění (např. hvězdičkou), nyní systém povinné údaje označí až po přechodu na další stránku. 

_Tato připomínka byla vznesena ze strany ČTŮ v rámci Pracovní skupiny pro otevřená data._

**Comment by jakubklimek** [comment]
Ono to tam označené je, ale použitá technologie (vuetify.js) od jisté verze přestala hvězdičku zobrazovat. Podíváme se na to.

**Comment by jakubklimek** [comment]
Vzhledem k tomu že nepovinných údajů je méně, označíme nepovinné řetězcem "(volitelné)" a "(optional)"
