### ISSUE TITLE
Allow users to upload registration file to the form (as a template)

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#63]
The user may want to upload once downloaded registration file to continue editing it. Currently, there is no option for that.

**Comment by skodapetr** [comment]
Should we allow for upload also for deleting a record?

**Comment by jakubklimek** [comment]
No, for that you have the trash can button.

**Comment by jakubklimek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Přidat možnost do formuláře nahrát stažený soubor](https://trello.com/c/W9ivEgWw/33-p%C5%99idat-mo%C5%BEnost-do-formul%C3%A1%C5%99e-nahr%C3%A1t-sta%C5%BEen%C3%BD-soubor)
