### ISSUE TITLE
Indicate editing mode and allow users to unlink from the original dataset

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkd-formulare#64]
Currently, there is no indication that the form is in "edit" mode, i.e. it knows the IRI of the edited dataset - this may be confusing.

In addition, when we have that indication, we should allow users to unlink from the original dataset, basically creating a copy.

**Comment by skodapetr** [comment]
IMHO. these should be two separate issues.

**Comment by skodapetr** [comment]
Any suggestions of how the hint should be implemented?

**Comment by jakubklimek** [comment]
There is also another use case for this (a reverse use case) - when used for local catalogs, we need to allow people to specify the new IRI of the dataset so that they do not have to edit the JSON-LD file manually.

I see three options the user can choose from (e.g. in Summary):
1. Create new dataset in NKOD => default when Dataset IRI is not received from DAV. When switched to from "Edit dataset in NKOD", it does not include the dataset IRI in the downloaded file
2. Edit dataset in NKOD => keep the Dataset IRI from DAV, default when IRI from DAV received
3. Create dataset in LKOD => allows to specify Dataset IRI manually (and displays some helpful message).

### Implementation

The download button will say:
1. Stáhnout nový záznam pro NKOD / Download new NODC record
2. Stáhnout editační záznam pro NKOD / Download editing NODC record
3. Stáhnout nový záznam pro LKOD / Download new LODC record

Next to it (to the right) there should be a [settings icon](https://material.io/resources/icons/?search=settings&icon=settings&style=baseline) button opening a dialog. Its tooltip:
Změnit typ záznamu / Change record type

In the dialog (title: Změnit typ záznamu / Change record type), there will be a select with the three options.
When option 3 is selected, dataset IRI input will be visible.

Tip text: "Uveďtě HTTPS IRI datové sady dle pravidel vašeho lokálního katalogu"/"Enter HTTPS IRI of the dataset according to rules of your local catalog"

**Comment by skodapetr** [comment]
I believe that the second label should be "Sáhnout editační záznam"  as it can be used for NKOD as well as LKOD.

**Comment by skodapetr** [comment]
When coming to an empty form it is not clear whether user want's to create a new NKOD or LCOD dataset. Using NKOD by default is better for NKDO users, but can confusing for LCOD users who may think they got the to wrong page.

**Comment by jakubklimek** [comment]
> I believe that the second label should be "Sáhnout editační záznam" as it can be used for NKOD as well as LKOD.

Not exactly. The edit record works only in NKOD. There is no such thing as edit for LKOD (as LKOD now is simply a list of records - there are no actions such as edit or delete).

LKOD users will know what to expect, so that is fine

**Comment by skodapetr** [comment]
What is not working?

**Comment by jakubklimek** [comment]
It is working OK. We are just discussing here.
